### ISSUE TITLE
Invalid Product Id for Auto-Renewable-Subscription

### ISSUE THREAD

**Issue by Zerocool27** [bizz84/SwiftyStoreKit#158] opened 2017-03-06 23:45 UTC
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [ ] Production

### Version
0.8.2
### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary

Always getting invalid product id error.

### What did you expect to happen

When I click the button for do-purchase the app always gives invalid product id error even though app bundle id and the purchase id is correct.Cannot even get to stage where user enters sandbox user credentials.

**Comment by quantumproducer** [comment] 2017-03-07 21:06
Hi, I am successfully able to create a subscription with a Sandbox account...
However, I am unable to reproduce this in a cURL. I am logging out the `self.base64encodedString` and using my shared secret password but Apple's servers reject the request with `21001`.

http://stackoverflow.com/questions/42656273/in-app-purchase-swifty-store-kit-showing-valid-purchase-curl-shows-error-code-2

If you are still getting that error within Swifty, validate that you have set your in app purchase item's metadata and checked "Cleared for Sale" in iTunes Connect.

Sign out of iTunes on your device then use a Sandbox account to sign in when prompted.

Sandbox will not work in iOS Simulator.

**Comment by bizz84** [comment] 2017-03-09 17:28
May be related to #154

**Comment by Sam-Spencer** [comment] 2020-05-30 02:58
Closing as a duplicate of #154.

**Closed by Sam-Spencer** 2020-05-30 02:58 UTC
Labels: duplicate
