### ISSUE TITLE
Why i'm getting this pop-up first time?

### ISSUE THREAD

**Issue by JaydeepVirani303** [bizz84/SwiftyStoreKit#638] opened 2021-06-09 17:50 UTC
## Bug Report
When I'm purchasing an in-app purchase the first time, I got this type of pop-up, then after clicking on multiple time download button, there is nothing happen and I can not purchase the product. Now after trying to purchase a second time, it is work and successful dialog came. I don't know why this happing for the very first time. Anyone can help me to fix this issue?

![image](https://user-images.githubusercontent.com/54850134/121403910-09f1cf00-c979-11eb-8ace-d88016849a3f.png)

Expected behavior
It should work the very first time, we should not give the option to download.

Platform Information
OS: [e.g. iOS 14.5.1]
Purchase Type: [e.g. non-consumable]
Environment: [e.g. sandbox]
SwiftyStoreKit version: [e.g. 0.16.1]

Screenshots
This is my code, please check it.

![image](https://user-images.githubusercontent.com/54850134/121404104-3efe2180-c979-11eb-8417-f6b085e90520.png)

**Comment by Sam-Spencer** [comment] 2021-06-18 04:29
Looks like this is a duplicate of #406. I'm closing this for now. If this is a different issue, let me know and I'll re-open!

**Closed by Sam-Spencer** 2021-06-18 04:29 UTC
Labels: type: bug
