### ISSUE TITLE
Can iOS 11 & XCode 9 work?

### ISSUE THREAD

**Issue by mouse-lin** [bizz84/SwiftyStoreKit#274] opened 2017-09-23 08:02 UTC
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [ ] Production

### Version
0.10.7

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary

When I click purchase button both demo and my app code can not work.  It let me sign in my test account twice and got 'Unknown error. Please contact support' message.

### What did you expect to happen
ℹ Please replace this with what you expected to happen.

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by rebeloper** [comment] 2017-09-25 09:32
Same here.

**Comment by mouse-lin** [comment] 2017-09-26 07:44
Hi @bizz84  I need some help. Thank you.

**Comment by jorgelp94** [comment] 2017-09-26 16:51
Same here.

**Comment by mouse-lin** [comment] 2017-09-26 18:17
@jorgelp94 Your app is running in the Simulator or real device IAP worked after you a new sandbox account.

**Comment by jorgelp94** [comment] 2017-09-26 18:29
Running on a real device

**Comment by BCtopics** [comment] 2017-09-29 18:11
I'm having no luck with this. Just getting a contact customer support error.

**Comment by mouse-lin** [comment] 2017-09-29 18:28
Hi @BCtopics , you can print the error after purchased failed. I believe you will get the same result with me.
It seems like iOS 11 bug has not yet been fixed.

[https://forums.developer.apple.com/message/261428#261428](url)

**Comment by bizz84** [comment] 2017-10-12 20:43
@mouse-lin Apologies for the very late reply.

I've been unable to make purchases recently on iOS 11, which seems to be a common problem as you reported.

In the end I managed to get things working again by creating a new sandbox user and trying a few times.

Could you try the same?

**Comment by funkenstrahlen** [comment] 2017-12-06 14:28
I use Xcode 9 and iOS 11 and can not reproduce this error any more. Seems fixed by Apple.

**Comment by bizz84** [comment] 2017-12-29 19:17
@mouse-lin is this still an issue or can it be closed?

**Closed** 2020-03-21 23:17 UTC
Labels: type: apple bug
