### ISSUE TITLE
Constant Popup

### ISSUE THREAD

**Issue by WillMays1** [bizz84/SwiftyStoreKit#288] opened 2017-10-15 19:33 UTC
### Platform
- [ ] iOS

### In app purchase type
- [ ] Auto-Renewable Subscription

### Environment
- [ ] Sandbox
- [ ] Production

### Version
ℹ Latest

## Report

Constant pops asking for apple id password even when app is closed. At least 2 an hour.

**Comment by SirComet** [comment] 2017-11-09 00:40
I have the same issue, don't know what is causing it, tried removing observer from AppDelegate, that didn't work.

**Comment by jecourte** [comment] 2017-11-12 00:34
I think this happens when you're testing and you don't complete a transaction.  You'll have to restore the transaction that hangs in limbo.

**Comment by WillMays1** [comment] 2017-11-12 00:35
How do I restore the transaction

**Comment by SirComet** [comment] 2017-11-13 17:15
hmm...but I am certain every transaction is finished during payments and even when starting the app.

So what other transaction is hanging and how do I fix it.  

I restored the observer in the the AppDelegate and nothing is different, changed to atomic and non-atomic, same result... (normal app functioning is atomic) 

it happens on every device doesnt matter if its via testflight or direct-debug install via xcode. 

code for purchases is : 

```
func purchase(_ purchase: RegisteredPurchase){
        NetworkActivityIndicatorManager.networkOperationStarted()
        SwiftyStoreKit.purchaseProduct(appBundleId + "." + purchase.rawValue, atomically: true) { result in
            NetworkActivityIndicatorManager.networkOperationFinished()

            if case .success(let purchase) = result {
                //purchase sent to queue.
                if purchase.needsFinishTransaction {
                    SwiftyStoreKit.finishTransaction(purchase.transaction)
                }
            }
    }
}


```

**Comment by weakfl** [comment] 2017-11-17 12:07
I'm having the same issue.
`completeTransactions()` comes up empty, same for `restorePurchases()`.

**Comment by weakfl** [comment] 2017-11-20 12:12
I've finally been able to resolve this issue by closely examining the receipt during validation on our server.
It turned out there were indeed some (non-atomic) purchases that hadn't been finished (`finishTransaction()` had never been called due to a server-side bug).

**HOWEVER:**
**None of these purchases ever turned up in `completeTransactions()`!** I had to re-purchase the unfinished consumables (which will trigger a _"You have already purchased this item"_ message) until the receipt was clean again.

I'm not sure if there's a bug in `completeTransactions()` or what else might be the cause of this issue, but at least I don't get the annoying pop-ups anymore...

**Comment by funkenstrahlen** [comment] 2017-12-08 19:45
I have the same issue. Really do not know what to do.

**Comment by bizz84** [comment] 2017-12-22 16:47
Apologies for the late reply everyone. I have just found a bug in `completeTransactions`. See #322. Fix is in progress.

The problem is that calling `completeTransactions()` with **`atomically: false`** does not finish **failed** transactions.

If there isn't a logged in Apple ID, it may be that StoreKit asks to Sign In so it can progress unfinished transactions (however this is just my guess).

**Comment by WillMays1** [comment] 2017-12-22 18:30
Please update us when the bug is fixed. Thanks.

**Comment by funkenstrahlen** [comment] 2017-12-22 19:20
@WillMays1 Changes are already in develop branch. You can check if this fixes the problem for you.

**Comment by bizz84** [comment] 2017-12-23 11:02
Available on version [0.11.3](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.11.3).

**NOTE**: While this closes a bug in `completeTransactions()`, it doesn't guarantee the login popup stops appearing.

**Comment by bizz84** [comment] 2017-12-23 11:06
About this comment:

> I think this happens when you're testing and you don't complete a transaction. You'll have to restore the transaction that hangs in limbo.

Transactions that have _completed_ (either `.purchased`, `.restored` or `.failed`) will be captured by `completeTransactions` if this is called correctly.

It's possible that any transactions in progress trigger the login popup if the user is not signed in, even outside the app. 

Once signed in though, transaction should eventually become `.purchased`, `.restored` or `.failed`, and caught by `completeTransactions` the next time the app runs.

Did anyone observe login popups appearing over and over, even after entering username and password?

**Comment by huyduc** [comment] 2018-01-08 09:41
>Did anyone observe login popups appearing over and over, even after entering username and password?
@bizz84 Yes, it never stops, no matter how many times we enter the password

**Comment by funkenstrahlen** [comment] 2018-01-21 16:16
> Did anyone observe login popups appearing over and over, even after entering username and password?

Yes.

**Comment by jeanfw** [comment] 2018-03-05 22:21
> Did anyone observe login popups appearing over and over, even after entering username and password?

Yes (with 0.13.1)

**Comment by funkenstrahlen** [comment] 2018-03-06 04:04
@jeanfw have you tested with iOS 11.3 beta? There are some reports the issue is gone with iOS 11.3.

**Comment by funkenstrahlen** [comment] 2018-04-07 06:07
This should be fixed in iOS 11.3. Please close this issue if you can confirm.

**Comment by jeanfw** [comment] 2018-04-13 15:10
I kept being prompted on 11.3. Canceling the dialog resulted in being prompted again later. Unlike on previous versions, however, entering my password seems to have stopped the prompting for good. It's been a few days already so it seems to me it's fixed 🎉. 

I can't close the issue myself, so @funkenstrahlen feel free to!

**Comment by funkenstrahlen** [comment] 2018-04-13 15:27
Yes you have to enter your password one more time after upgrading to 11.3. Then the popup is gone.

I can not close the issue either.

**Closed** 2020-05-29 22:56 UTC
Labels: area: purchase flows
