### ISSUE TITLE
Handle "Already purchased"?

### ISSUE THREAD

**Issue by gerchicov-bp** [bizz84/SwiftyStoreKit#178] opened 2017-04-05 08:23 UTC
### Platform

- [x] iOS

### In app purchase type

- [x] Auto-Renewable Subscription

### Environment

- [x] Sandbox

### Version
0.8.4

### Issue summary
1) Buy a subscription
2) In its completion block verify receipt
3) Try to buy a subscription again

### What did you expect to happen
1) and 2) called with their completion blocks. And possibility to handle "you have already bought a subscription" alert somehow.

### What happened instead
sometimes 1) and/or 2) doesn't called but "you have already bought a subscription" alert appears and I can't handle the result that it has been already bought. And it seems there are no handlers for this situation

**Comment by bizz84** [comment] 2017-04-24 15:20
**NOTE**: The "you have already purchased ..." alert is an internal step performed by StoreKit when purchasing a product and there is no way to intercept it directly (AFAIK). Note that the user is not charged again when this alert appears.

I'm going to close this as a duplicate of #183. Please post any more questions there if needed.

**Closed by bizz84** 2017-04-24 15:20 UTC
