### ISSUE TITLE
Update Cocoapods spec

### ISSUE THREAD

**Issue by wimbledon** [bizz84/SwiftyStoreKit#546] opened 2020-06-17 05:41 UTC
Update to the latest 0.16.0 on https://github.com/CocoaPods/Specs
The current version is still 0.15.0.
@Sam-Spencer and @RomanPodymov

**Comment by Sam-Spencer** [comment] 2020-06-17 16:59
Please see the pinned issue. Closing this as a duplicate of #541.

**Closed by Sam-Spencer** 2020-06-17 16:59 UTC
Labels: type: enhancement
