### ISSUE TITLE
paymentQueue marked unavailable on macOS

### ISSUE THREAD

**Issue by legolasW** [bizz84/SwiftyStoreKit#520] opened 2020-02-14 09:35 UTC
### Platform

- [ ] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [ ] Production

### Version
ℹ Please replace this with the version of SwiftyStoreKit you're using.

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
ℹ Please replace this with an explanation of the issue, including reproduction steps.

### What did you expect to happen
ℹ Please replace this with what you expected to happen.

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by Sam-Spencer** [comment] 2020-02-18 22:17
Closing as duplicate of #484

**Closed by Sam-Spencer** 2020-02-18 22:17 UTC
Labels: area: new technologies, duplicate, macOS Catalyst, type: bug
