### ISSUE TITLE
SwiftyStoreKit 0.10.3 isn't building on Xcode 9 Beta 2 even in Swift 3 exclusive projects

### ISSUE THREAD

**Issue by ethanwa** [bizz84/SwiftyStoreKit#234] opened 2017-06-23 17:21 UTC
### Platform

- iOS

### Version
0.10.3 via Pod file

## Report
I am trying to get the current Swift 3 version of SwiftyStoreKit to work on Xcode 9 Beta 2. I don't want to update my project to Swift 4 just yet, but I do want to use Xcode 9 for the new features, such as faster build system, better warnings/fixes, etc. 

When I try to use SwiftyStoreKit on Xcode 9 and I am getting mostly "Use of unresolved identifier 'SKError'" errors. Can we fix this? Swift 4 is not a requirement of using Xcode 9, therefore SwiftyStoreKit should work with Xcode 9 even though it's in Swift 3.

Thank you!

<img width="274" alt="screen shot 2017-06-23 at 1 13 05 pm" src="https://user-images.githubusercontent.com/1653780/27493160-bd170d1c-5816-11e7-9c3e-62e7788b682d.png">

**Comment by stevapple** [comment] 2017-06-24 07:47
It's probably a change in iOS 11 SDK, as it also occur to Xcode 9 beta1.

**Comment by bizz84** [comment] 2017-06-24 09:04
@ethanwa try with the [swift-4.0](https://github.com/bizz84/SwiftyStoreKit/tree/swift-4.0) branch. I should probably rename it to `Xcode9` branch as it's actually compatible with Swift 3.

**Comment by ethanwa** [comment] 2017-06-24 17:23
Thanks bizz84, is there a specific way I should access this branch using my Pod file?

**Comment by bizz84** [comment] 2017-06-25 10:15
```swift
pod 'SwiftyStoreKit', :git => 'https://github.com/bizz84/SwiftyStoreKit', :branch => 'swift-4.0'
```

Also, see #225.

**Comment by bizz84** [comment] 2017-06-26 12:40
I'm going to close this as a duplicate of #225. Feel free to reopen and continue the discussion if needed.

**Closed by bizz84** 2017-06-26 12:40 UTC
Labels: answered, type: question

**Comment by massimobio** [comment] 2017-06-26 19:26
The swift-4 branch doesn't work in Xcode 8 but it works in Xcode 9 although the error handling is broken.
I was able to make the swift-4 branch compile in Xcode 8 as with a small change in the os.swift file:
```Swift

import StoreKit

// MARK: - missing SKMutablePayment init with product on OSX
#if os(OSX)
    extension SKMutablePayment {
        convenience init(product: SKProduct) {
            self.init()
            self.productIdentifier = product.productIdentifier
        }
    }
#endif

    // error codes for the SKErrorDomain
    public enum SKErrorCode: Int {
        
        case unknown
        case clientInvalid // client is not allowed to issue the request, etc.
        case paymentCancelled // user cancelled the request, etc.
        case paymentInvalid // purchase identifier was invalid, etc.
        case paymentNotAllowed // this device is not allowed to make the payment
    }
```

I'm not sure if that's the right thing to do and error handling is still an issue, but it would be great to be able to easily switch between Xcode 8 and 9 to test our apps for iOS 11 compatibility and to start taking advantage of the next refactoring features without compromising the ability to submit builds to the App Store with Xcode 8

**Comment by bizz84** [comment] 2017-07-16 15:02
As of Xcode 9 beta 3, SwiftyStoreKit compiles correctly on `master`.

I have deleted the `swift-4.0` branch as the library is now compatible with both Swift 3 and Swift 4.
