### ISSUE TITLE
What is the reason of this error "Unknown error. Please contact support" ?

### ISSUE THREAD

**Issue by X901** [bizz84/SwiftyStoreKit#376] opened 2018-06-02 18:00 UTC
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [x] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [ ] Production

Some user tell me they get this error "Unknown error. Please contact support"

I don't know what is the reason he get this error!

**Comment by X901** [comment] 2018-06-03 10:16
Anyone know what is the reason for this issue ? And how to fix it ?

**Comment by rafaelapaula** [comment] 2018-07-24 18:48
I have same problem, did you find a solution @X901 ?

**Comment by X901** [comment] 2018-07-24 18:52
@rafaelapaula Unfortunately I didn't find a solution 
I leave it as it is 
but I felt like I lose some customer with this issue =(

some users didn't had any issue , others had this issue
I don't understand what is the reason of this issue !

**Comment by bizz84** [comment] 2018-07-24 19:51
Hi everyone. Sorry for the late reply.

First of all, there is no code in the SwiftyStoreKit library that returns "Unknown error. Please contact support".

Instead, the sample demo application uses this string as a placeholder when an error has occurred but there is no message for it. So you would only get this error if you're using the same error handling code in the sample demo app.

So assuming you **are** using the same error handling code in the sample demo app, you could get this error in one of the following cases:

- you called `retrieveProductsInfo`, and StoreKit returns a response object with no products and no invalidProductIdentifiers. Not sure why this would happen and the Apple documentation is not clear about it.
- you called `restorePurchases`, but some purchases failed to restore.

Hope this is clearer.

**Comment by bizz84** [comment] 2018-07-24 19:56
By the way, this seems a duplicate of #169

**Closed** 2020-02-24 21:39 UTC
Labels: answered, duplicate, type: question
