### ISSUE TITLE
Invalid product ID pops when app is live on App Store, but not in testing.

### ISSUE THREAD

**Issue by antonijap** [bizz84/SwiftyStoreKit#162] opened 2017-03-10 10:47 UTC
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [x] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [x] Production

### Version
ℹ 0.8.2

### Issue summary
ℹ I have one in-app purchase and it works when I test it in Simulator and my own iPhone. I published an app and when a user downloads it, they get alert with message: Invalid product identifier

**Comment by bizz84** [comment] 2017-03-10 17:45
Closing this as duplicate of #154. Please follow the discussion there.

It seems like many users have been seeing Invalid Product Identifier errors in the last 2 weeks.

**Closed by bizz84** 2017-03-10 17:45 UTC
Labels: duplicate
