### ISSUE TITLE
Use of undeclared type 'SKError' on XCode 9 beta

### ISSUE THREAD

**Issue by wasappi** [bizz84/SwiftyStoreKit#225] opened 2017-06-06 10:20 UTC
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [x] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [ ] Production

### Version
0.10.3

### Issue summary
Using XCode 9 all SKError references are marked as error : Use of undeclared type 'SKError'

**Comment by codedifferent** [comment] 2017-06-07 03:18
My quickfix workaround: 

I just imported not only SwiftyStoreKit but also StoreKit into my AppDelegate:

```swift
//  AppDelegate.swift

import UIKit
import SwiftyStoreKit
import StoreKit
// ...
```

Hope this helps :-)

**Comment by adad184** [comment] 2017-06-07 07:54
same issue, no solution

**Comment by naveen2202** [comment] 2017-06-07 08:40
same issue

**Comment by JustinM1** [comment] 2017-06-07 09:02
possible temporary fix https://github.com/JustinM1/SwiftyStoreKit.git

project builds and passes all tests. not tested yet with real `StoreKit` interaction.

`pod 'SwiftyStoreKit', :git => 'https://github.com/JustinM1/SwiftyStoreKit.git', :branch => 'SKErrorFix'`

**Comment by JustinM1** [comment] 2017-06-07 09:11
possible temporary fix https://github.com/JustinM1/SwiftyStoreKit.git

project builds and tests pass. Not yet tested with real `StoreKit` interaction.

`pod 'SwiftyStoreKit', :git => 'https://github.com/JustinM1/SwiftyStoreKit.git', :branch => 'SKErrorFix'`

**Comment by huyduc** [comment] 2017-06-07 17:16
Seems to be bug in XCode 9? Let's file a radar?

**Comment by adad184** [comment] 2017-06-08 01:01
it's not a bug,   there's no SKError in iOS 11 SDK any more, it became the combination of NSError + SKErrorCode.

**Comment by bizz84** [comment] 2017-06-08 08:07
@JustinM1 Thank you for your fix. I have looked at this as well and came up with a slightly different approach (see #227).

Everyone, please note that changes made into the [`swift-4.0`](https://github.com/bizz84/SwiftyStoreKit/tree/swift-4.0) branch may break as new Xcode 9 betas are released. For now, the aim is to have a compilable version of SwiftyStoreKit.

**Comment by JustinM1** [comment] 2017-06-08 11:30
@bizz84 sure, no prob. I threw it together to get the project to build. Happy to see your taking a different approach for a longer term fix.

**Comment by bizz84** [comment] 2017-06-08 15:12
@JustinM1 At this stage, I don't think any specific approach is better or worse. In fact, things may change again before the final Xcode 9 release.

I'll be reviewing all Swift 4 changes before eventually merging back to master.

**Comment by bizz84** [comment] 2017-06-08 15:21
This is now fixed on branch [swift-4.0](https://github.com/bizz84/SwiftyStoreKit/tree/swift-4.0).

To install, use:

```ruby
pod 'SwiftyStoreKit', :git => 'https://github.com/bizz84/SwiftyStoreKit', :branch => 'swift-4.0'
```

**Closed by bizz84** 2017-06-08 15:21 UTC

**Comment by huyduc** [comment] 2017-06-08 23:47
@adad184 @bizz84 I just confirmed with StoreKit engineer in the lab, this is definitely a bug, SKError isnt goinf anywhere. Please file radar

**Comment by adad184** [comment] 2017-06-09 00:52
badnews :(, i downgraded the Base SDK of Xcode9 to fix it

**Comment by NateFuller** [comment] 2017-06-12 21:10
@huyduc So it's safe to say we *should* be able to still cast an SKPaymentTransaction object's `error` property as an SKError object? I'm assuming it should have some sort of `errorCode` property that we use SKErrorCode values to compare to?

**Comment by fishcharlie** [comment] 2017-06-21 23:25
Still not working in beta 2

**Comment by fishcharlie** [comment] 2017-06-26 06:05
@bizz84 Is this branch backwards compatible with Xcode 8.3.3 and such? I want to start using Xcode 9 but I’m concerned that using this branch will cause problems when I want to deploy or build on Xcode 8.3.3. Any insight?

**Comment by bizz84** [comment] 2017-06-26 12:39
@fishcharlie Apple has removed the `SKError` type and added `SKErrorCode` on Xcode 9, and this makes the two branches **not** compatible with each other.

As I plan to maintain both `master` and `swift-4.0`, I suggest to just use the one that is compatible with your Xcode version you're currently using, and switch as needed.

**Comment by fishcharlie** [comment] 2017-07-10 18:31
This is fixed in Xcode 9 beta 3. Using the master branch in Xcode 9 beta 3 doesn't produce any errors when building.

**Comment by innoreq** [comment] 2017-08-06 11:17
Tried explicit master branch with XC9/4, does not work. Still "Use of undeclared type SKError".

**Comment by fishcharlie** [comment] 2017-08-06 15:41
@innoreq Have you cleaned your project? Every version after and including Xcode 9 Beta 3 so far has not had this problem. So it definitely sounds like a problem on your system.
