### ISSUE TITLE
JSONDecodeError(Optional(""))??

### ISSUE THREAD

**Issue by michaelsousa21** [bizz84/SwiftyStoreKit#57] opened 2016-07-14 01:35 UTC
I keep getting this error when I try to verify the receipt. How can I fix this?
I'm running the iOS version on xcode 7.3.1

**Debug Output:**
CoreFoundation = 1145.150000
Purchase Success: com.testapp.inapp10
Verify receipt Failed: JSONDecodeError(Optional(""))

**Comment by phimage** [comment] 2016-07-19 20:08
In `InAppReceipt`, `verify`function we receive `safeData` so no `.NoRemoteData` error
But data seems empty so no receiptInfo. Maybe another exception must be throw for that case.

**Comment by odedharth** [comment] 2016-08-06 10:30
Also received this error after a verification of a successful purchase. 
Any update on this?

**Comment by bizz84** [comment] 2016-08-08 10:46
I created a PR to return .NoRemoteData when the receipt data is empty: https://github.com/bizz84/SwiftyStoreKit/pull/64

@odedharth @michaelsousa21 Can you try running on this branch? https://github.com/bizz84/SwiftyStoreKit/tree/feature/JSONDecodeError-empty-data

Note that with this change receipt verification will still fail, it just returns a different error case.

**Comment by odedharth** [comment] 2016-08-11 13:14
@bizz84 As I understand the problem it seems that from some reason the purchase succeeds but the verification is failing.  So I'm wondering that maybe the problem is with the purchase function, and not the verification function. Because if a purchase succeeds the verification should be successful.

**Comment by nhantrivinh** [comment] 2016-09-12 03:26
So  my purchase succeeded but my verification fail. However, my verification did not fail at first but then "one day" it failed. Something must have changed perhaps on iTunes Connect.

**Comment by bizz84** [comment] 2016-10-19 22:00
@michaelsousa21 @nhantrivinh I still need to investigate this further. I'm going to label this as a bug for now.

**Comment by HyunjoonKo** [comment] 2017-01-16 08:41
Hi. 

The same thing happened to me. The user succeeded in the purchase, but the receipt was not decoded, so the app failed to purchase it. So the user made 10 payments in a row. Is there a way to avoid this?

**Comment by bizz84** [comment] 2017-02-20 23:50
There have been some significant improvements to the purchase flows recently.

@michaelsousa21 @nhantrivinh @HyunjoonKo can you retest this with the latest version, and let me know if it works correctly now?

**Comment by bizz84** [comment] 2017-05-11 17:36
Closing this issue. Feel free to open a new one if there are still issues. Current release is [0.9.0](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.9.0).

**Closed by bizz84** 2017-05-11 17:36 UTC
Labels: bug
