### ISSUE TITLE
Pass data from purchaseProduct to completeTransactions

### ISSUE THREAD

**Issue by gerchicov-bp** [bizz84/SwiftyStoreKit#268] opened 2017-09-11 09:35 UTC
### Platform

- [x] iOS

### In app purchase type

- [x] Auto-Renewable Subscription

### Environment

- [x] Sandbox
- [x] Production

### Version
0.10.2

### Related issues
https://github.com/bizz84/SwiftyStoreKit/issues/266
https://github.com/bizz84/SwiftyStoreKit/issues/185

### Issue summary
My current goal is to pass some data from `SwiftyStoreKit.purchaseProduct` to `SwiftyStoreKit.completeTransactions`. The data is not related to `SwiftyStoreKit` and `StoreKit`. This data is up-to-date during `SwiftyStoreKit.purchaseProduct` callback and may be out-of-date in `SwiftyStoreKit.completeTransactions` callback. The data is linked with concrete transaction.

### What did you expect to happen
Possibility to somehow pass data from `SwiftyStoreKit.purchaseProduct` to `SwiftyStoreKit.completeTransactions`.

### What happened instead
The problem is you allow to declare `SwiftyStoreKit.completeTransactions` once only and it is common for all callbacks.

**Comment by bizz84** [comment] 2017-10-11 14:16
@gerchicov-bp the purpose of `completeTransactions` is to register a transaction observer and finish any transactions that may have been completed after the app was closed (StoreKit alerts run on a separate process to your app).

It is not possible to pass data from `SwiftyStoreKit.purchaseProduct` to `SwiftyStoreKit.completeTransactions` by design.

What information do you need that is available in `purchaseProduct` but not in `completeTransactions`?

**Comment by bizz84** [comment] 2017-12-29 20:58
This issue was not updated in a while so I'm closing it.

**Closed by bizz84** 2017-12-29 20:58 UTC
Labels: type: question
