### ISSUE TITLE
SwiftyStoreKit.completeTransactions - completion block may not be called

### ISSUE THREAD

**Issue by gerchicov-bp** [bizz84/SwiftyStoreKit#171] opened 2017-03-27 14:16 UTC
### Platform

- iOS

### In app purchase type

- [ ] Auto-Renewable Subscription

### Environment

- [ ] Sandbox

### Version
branch - master

### Issue summary
From your readme - ```SwiftyStoreKit.completeTransactions``` has completion block which may not be called.

### What did you expect to happen
The completion block should be called anyways - with error and/or with empty array of results.

### What happened instead
The completion block is usually not called at all

**Comment by bizz84** [comment] 2017-04-24 15:26
@gerchicov-bp apologies for the late reply.

This is expected, as explained in #187.

Closing this as a duplicate of #187, please ask any more questions there if needed.

**Closed by bizz84** 2017-04-24 15:26 UTC
