### ISSUE TITLE
How to use this in Objective C projects 

### ISSUE THREAD

**Issue by shaktiprakash099** [bizz84/SwiftyStoreKit#383] opened 2018-06-27 07:33 UTC

**Comment by shaktiprakash099** [comment] 2018-07-12 04:54
@paoloandrea  Actually i could not able to use this in my objective c project  so i have created   a  helper class related to SKPayment where i have written all SKPayment delegates and receipt validation stuffs and functionality .i al just sending my product identifier and the helper class does everything for including validating the transaction receipt.

**Comment by bizz84** [comment] 2018-07-24 19:59
Apologies for the late reply.

This is a duplicate of https://github.com/bizz84/SwiftyStoreKit/issues/123.

Also as stated [here](https://github.com/bizz84/SwiftyStoreKit/blob/master/CONTRIBUTING.md#scope), ObjC support is a non-goal for SwiftyStoreKit.

I've had very little time to devote to this project this year so it's very unlikely that this will happen. Feel free to fork and add support in your own version.

**Closed by bizz84** 2018-07-24 19:59 UTC
