### ISSUE TITLE
Failed for macOS app sometimes

### ISSUE THREAD

**Issue by chaocharleswang** [bizz84/SwiftyStoreKit#359] opened 2018-04-03 15:33 UTC
### Platform

- [ ] iOS
- [x] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [x] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [x] Production

### Version
0.13.1

### Issue summary
I used your library on my macOS app. However, some customers complain they cannot purchase my product.

**Comment by Sam-Spencer** [comment] 2020-05-29 23:24
Closing as possible duplicate of #347.

**Closed by Sam-Spencer** 2020-05-29 23:24 UTC
