### ISSUE TITLE
Promo codes stopped working

### ISSUE THREAD

**Issue by ramiechaarani** [bizz84/SwiftyStoreKit#488] opened 2019-09-09 16:26 UTC
<p align=center><b>DUPLICATE OF #262</b></p><hr/>

### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [x] Production

### Version
Latest

### Issue summary
I was having my users use promo codes to redeem a free month of an auto renewing subscriptions but since about the beginning of september it has not been registering. 

I tried to click on restore with no luck and I even tried restarting/redownloading the app with no luck.

What could have changed between this month and last? 

### What did you expect to happen
I was expecting the promo codes to work

### What happened instead
They did not work and are still not working

**Comment by aalenliang** [comment] 2019-09-10 07:49
My users give me the same feedback about redeem code not working, any idea how to test it?
BTW my IAP is non-consumable.

**Comment by ohlsson** [comment] 2019-09-23 18:09
Same issue for me.

**Comment by Sam-Spencer** [comment] 2020-03-21 23:29
Hmm... this sounds like it might be an issue on Apple's side. Are you referring to actual promo codes that you generate and distribute yourself, which can then be redeemed like gift cards? Or are you referring to promotional periods / offers for subscriptions?

**Comment by Sam-Spencer** [comment] 2020-06-07 21:22
Turns out this is a duplicate of #262! Check the 0.17 milestone for progress!

**Closed** 2020-06-07 21:24 UTC
Labels: duplicate
