### ISSUE TITLE
When support with ipad to Mac 10.15 ?

### ISSUE THREAD

**Issue by CNOJAME** [bizz84/SwiftyStoreKit#510] opened 2020-01-05 08:37 UTC
### Platform

- [x] iOS
- [x] macOS
- [ ] tvOS

### In app purchase type

- [x] Consumable
- [x] Non-consumable 
- [x] Auto-Renewable Subscription
- [x] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [x] Production

### Version
0.15

### Related issues
ℹ When compiling for Xcode on macOS 10.15+, an error occurs.

### Issue summary
When compiling Xcode shows the error below:
/xxxxxx/Pods/SwiftyStoreKit/SwiftyStoreKit/PaymentQueueController.swift:244:10: Cannot override 'paymentQueue' which has been marked unavailable
Error function:
 #if os(iOS)
    func paymentQueue(_ queue: SKPaymentQueue, shouldAddStorePayment payment: SKPayment, for product: SKProduct) -> Bool {
        
        return shouldAddStorePaymentHandler?(payment, product) ?? false
    }

### What did you expect to happen
Should not show an error

**Comment by Sam-Spencer** [comment] 2020-02-18 22:16
Closing as a duplicate of #484

**Closed by Sam-Spencer** 2020-02-18 22:16 UTC
Labels: area: new technologies, duplicate, macOS Catalyst
